name: Stargazing Forecast Execution Schedule

on:
  schedule:
    - cron: '0 8,20 * * *' # runs @ 8AM/8PM UTC
  workflow_dispatch: # allows manual triggers

jobs:
  run-stargazing-flow:
    runs-on: ubuntu-latest

    env:
        # R2 credentials
        R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
        R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
        # prefect credentials
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        # github credentials
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install GDAL system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
          export GDAL_VERSION=$(gdal-config --version)
          echo "GDAL_VERSION=$GDAL_VERSION" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: |
          pip install GDAL==$(gdal-config --version)
          pip install -r requirements.txt

      - name: Run orchestration flow
        run:  |
          cd prefect
          python -c "from orchestration import stargazing_orchestration_flow; stargazing_orchestration_flow()"
