name: Stargazing Forecast Test Execution

on:
  schedule:
    - cron: '0 8,20 * * *' # runs @ 8AM/8PM UTC
  workflow_dispatch: # allows manual triggers

jobs:
  test-stargazing-gif:
    runs-on: ubuntu-latest
    environment: stargazing-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install GDAL system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
      
      - name: Install dependencies
        run: |
          pip install GDAL==$(gdal-config --version)
          pip install -r requirements.txt
      
      - name: Run stargazing calculation flow
        env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
        run: |
          python -c "from flows import test_stargazing_gif_flow; test_stargazing_gif_flow()"

 